quick_links:
  type: objects
  default:
    [
      { "question": "What exactly is vaccine risk?" },
      { "question": "Should I be concerned about aluminum?" },
      { "question": "Can vaccines induce food allergies?" },
    ]
  schema:
    name: "link"
    identifier: question
    properties:
      question:
        type: string
        required: true

recent_conversations:
  default: 15
